exports.apiEnum = {
    API_SIGNUP: "/auth/signup",
    API_LOGIN: "/auth/login",
    API_GET_TOKEN: "/auth/token",
    API_FORGOT_PASSWORD: "/forgot-password",
    API_RESET_PASSWORD: "/reset-password/:token",
    API_UPDATE_PASSWORD: "/auth/update-password",
    API_GET_MY_PROFILE: "/auth/my-profile",
    API_UPDATE_PROFILE: "/auth/update-details",
    API_DELETE_ME: "/auth/delete-me",
    API_GET_ALL_USERS: "/auth/users",
    API_GET_REVIEW: "/reviews/:id",
    API_GET_ALL_REVIEWS: "/reviews",
    API_CREATE_REVIEWS: "/reviews",
    API_CREATE_REVIEWS_INSIDE_ROUTER: "/tours/:tourId/reviews",
    API_TOUR: "/auth/tours/:id",
    API_CREATE_TOUR: "/auth/tours",
    API_GET_USER : "/auth/users/:id",
}